### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by mcmahonjohn** [mcmahonjohn/probot-arborist#4]
## Goals for Project

- [X] Arborist starts properly
- [ ] Arborist reads the config file ([used the setting.js file from probot-settings](https://github.com/probot/settings/blob/master/lib/settings.js))
- [X] Arborist catches events when a branch is created
- [X] Arborist catches events when an issue is created by the bot
- [ ] Arborist validates the branch against the configuration setting
- [X] Arborist creates an issue for a branch that doesn't meet naming convention
- [ ] Arborist updates existing issue for any new branches that don't meet naming convention
- [ ] Arborist creates an issue for Pull Request that is closed, but the branch hasn't been deleted
- [ ] Arborist creates an issue for Pull Request that is merged, but the branch hasn't been deleted
- [ ] Arborist updates existing issue for any Pull Requests that are closed, but the branch hasn't been deleted
- [ ] Arborist updates existing issue for any Pull Requests that are merged, but the branch hasn't been deleted
- [ ] Add support for Arborist deleting branches based on configuration setting. (Currently, [node-gtthub](https://mikedeboer.github.io/node-github/) doesn't support deleting branches
- [ ] Arborist monitors created issues for any that get closed/completed.
- [ ] Arborist creates new issues when conditions are met after previous issues are closed.
